# Generated by Django 5.0.3 on 2024-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('sku', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(default='single', max_length=128)),
                ('price', models.FloatField(blank=True, help_text='Enter the price of the product.', null=True, verbose_name='Product Price')),
                ('description', models.TextField(blank=True)),
                ('short_descriptions', models.TextField(blank=True)),
            ],
        ),
    ]
