# Generated by Django 5.0.3 on 2024-03-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_short_descriptions_product_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('parant_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=180, unique=True)),
            ],
        ),
    ]
