# Generated by Django 5.0.3 on 2024-03-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
