# Generated by Django 5.0.3 on 2024-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parant_id',
            field=models.IntegerField(),
        ),
    ]
